export const ACCOUNTS = [
  "YOK",
  "Türkiye Finans Katılım Bankası",
  "Akbank",
  "Türk Ekonomi Bankası",
  "Yapı Kredi Bankası",
  "OBSS Teknoloji",
  "Unico",
  "BKT",
  "OBSS Bilişim",
  "Erka Turizm",
  "Allianz Sigorta",
  "Turkcell",
  "Anadolu Sigorta",
  "Türkiye İş Bankası",
  "eBay",
  "Vakıfbank",
  "AktifBank",
  "Aslanoba",
  "Witwise",
  "Aksigorta",
  "OBSS Mobile",
  "EnerjiSA",
  "Exceller-8",
  "Garanti Teknoloji",
  "Yapı Kredi Yatırım",
  "Hürriyet",
  "Multinet",
  "Koton",
  "Cigna Finans Emeklilik ve Hayat A.Ş",
  "Vakko",
  "Aselsan",
  "Bankalararası Kart Merkezi",
  "Borusan",
  "LeasePlan",
  "ING Bank",
  "LC Waikiki",
  "Doğuş Teknoloji",
  "Sağlık Bakanlığı",
  "ÖSYM",
  "SoftTech",
  "Sprongo",
  "Sony",
  "The International Bank of Azerbaijan",
  "TÜBİTAK",
  "Cat Güvenlik",
  "test",
  "account10",
  "account100",
  "Ankara",
  "Faculty of Science and Literature",
];

export const ROLES = [
  "Content Manager",
  "Exam Creator",
  "Guest",
  "HR",
  "Interviewer",
  "Pool Manager",
  "Resource Planer",
  "Session Template Creator",
];

export const DEPARTMENTS = [
  "asd@asd.com",
  "Software Development Group",
  "Forms to Java Group",
  "Test Group",
  "Software Architecture Group",
  "Account Management",
  "Project Management Office",
  "Other",
  "Analyst Group",
  "Executive",
  "Administrative Affairs",
  "Visual Art Design",
  "Business Development",
  "Research and Developement Group",
  "One Cycle Group",
  "Atlassian",
  "Human Resources",
  "Release and Configuration Management",
  "Plug-in Development",
  "Robotics Group",
  "Engineering Team",
  "Accounting",
  "Financial Management",
  "Finance",
  "Corporate Communications",
  "Business Intelligence",
  "Business Development Team",
  "DevOps",
  "Systems Engineering Group",
  "Systems Design and Engineering",
  "test",
  "department10",
  "department100",
  "Marketing",
  "Maths",
  "İstanbul Teknik Üniversitesi",
];

export const EXPERTISES = [
  ".NET",
  "Accounting",
  "Analysis",
  "Android",
  "Architect",
  "Atlassian",
  "Brand Marketing",
  "Budget and Reporting",
  "Business Development",
  "Business Intelligence",
  "Buzz Marketing",
  "C++",
  "Calculus",
  "Cash Planning",
  "COBOL",
  "DevOps",
  "Devops Engineer",
  "Digital Marketing",
  "Engagement",
  "ETL Developer",
  "expertise10",
  "expertise100",
  "Field Engineer",
  "Finance",
  "Financial Management",
  "Front End",
  "Full Stack",
  "Internal Control",
  "iOS",
  "Java",
  "Linear Algebra",
  "Machine Learning",
  "Maths",
  "Other",
  "PHP",
  "Plug-in",
  "Project Management",
  "Purchasing",
  "React Native",
  "Receptionist",
  "Solution Architecture",
  "System Administration",
  "System Engineer",
  "Systems Engineer",
  "Technician",
  "Test",
  "UX Lead",
  "VB_EXP",
  "Visual Art Design",
  "Yeni Java",
];

export const LABELS = [
  "A",
  "ABC",
  "AHMET",
  "ALI",
  "CONFLUENCE",
  "DENEME________",
  "DSFSDF",
  "GIT_ACCESS",
  "IZIN",
  "LA",
  "LABEL10_1",
  "LABEL10_2",
  "LABEL10_3",
  "LABEL100_1",
  "LABEL100_2",
  "LABEL100_3",
  "LABEL101_1",
  "LABEL101_2",
  "LABEL101_3",
  "LABEL102_1",
  "LABEL102_2",
  "LABEL102_3",
  "MANAGER",
  "MENTOR",
  "NG2019",
  "OFF",
  "OFF2",
  "ON",
  "PROF",
  "SA",
  "SM2019",
  "SS",
  "STAJ2019",
  "TE",
  "TES",
  "TEST",
  "VB_2019",
  "VB_2020",
  "VB_2021",
  "VELI",
  "VICE-DEAN",
  "YENIMEZUN2019",
];

export const GENDERS = ["MALE", "FEMALE"];
